### ISSUE TITLE
Is Meros privacy respecting cryptocurrency?

### ISSUE THREAD

**Issue by Joe23232** [MerosCrypto/Meros#298]
Hi I wanted to know is Meros a privacy respecting cryptocurrency like [Beam](https://beam.mw/) for example?

**Comment by kayabaNerve** [comment]
First of all, I have a hard time calling MimbleWimble private due to the lack of privacy around senders/receivers. Yes, they're *eventually* aggregated into a indistinguishable set, yet they start isolated and therefore trackable. A network attack against Grin (also MW based) obtained 96% of senders/receivers.

This can be heavily reduced by efficient routing, I know Beam is a different coin, they do have Dandelion... I just dislike how they don't actually have any privacy tech for the senders/receivers proper. It's really just amount privacy + obfuscation.

Second of all, I heavily respect privacy. That said, Meros will not launch with privacy due to the amount of effort needed to integrate a private cryptsystem. It's being actively discussed for a future hard fork, with my personal preference being CLSAG (though I'm keeping an eye on Triptych/Acturus as those could forever change ring signatures as we know them).

**Comment by kayabaNerve** [comment]
Closing this as an issue as it has no relevance to the project's source code. I don't mind having a discussion here, although our [Discord](https://discord.meroscrypto.io) would be better. That said, this shouldn't be an open issue (or an issue at all).

**Comment by Joe23232** [comment]
I see thank you
